// File automatically generated by swift-bridge.
#include <stdint.h>
void* __swift_bridge__$get_length(void* term);
void* __swift_bridge__$read_file(void* url);
void* __swift_bridge__$search(struct RustStr path, struct RustStr query);


