name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
        #   token: ${{ secrets.CI_TOKEN }}
        #   config-file: .github/release-please-config.json
        #   manifest-file: .github/.release-please-manifest.json
